python xview2_metrics.py val_scoring/default_lb/0/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_0.json
python xview2_metrics.py val_scoring/default_lb/1/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_1.json
python xview2_metrics.py val_scoring/default_lb/2/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_2.json
python xview2_metrics.py val_scoring/default_lb/3/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_3.json
python xview2_metrics.py val_scoring/default_lb/4/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_4.json
python xview2_metrics.py val_scoring/default_lb/5/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_5.json
python xview2_metrics.py val_scoring/default_lb/6/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_6.json
python xview2_metrics.py val_scoring/default_lb/7/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_7.json
python xview2_metrics.py val_scoring/default_lb/8/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_8.json
python xview2_metrics.py val_scoring/default_lb/9/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_9.json
python xview2_metrics.py val_scoring/default_lb/10/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_10.json
python xview2_metrics.py val_scoring/default_lb/11/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_11.json
python xview2_metrics.py val_scoring/default_lb/12/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_12.json
python xview2_metrics.py val_scoring/default_lb/13/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_13.json
python xview2_metrics.py val_scoring/default_lb/14/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_14.json
python xview2_metrics.py val_scoring/default_lb/15/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_15.json
python xview2_metrics.py val_scoring/default_lb/16/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_16.json
python xview2_metrics.py val_scoring/default_lb/17/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_17.json
python xview2_metrics.py val_scoring/default_lb/18/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_18.json
python xview2_metrics.py val_scoring/default_lb/19/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_19.json
python xview2_metrics.py val_scoring/default_lb/20/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_20.json
python xview2_metrics.py val_scoring/default_lb/21/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_21.json
python xview2_metrics.py val_scoring/default_lb/22/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_22.json
python xview2_metrics.py val_scoring/default_lb/23/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_23.json
python xview2_metrics.py val_scoring/default_lb/24/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_24.json
python xview2_metrics.py val_scoring/default_lb/25/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_25.json
python xview2_metrics.py val_scoring/default_lb/26/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_26.json
python xview2_metrics.py val_scoring/default_lb/27/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_27.json
python xview2_metrics.py val_scoring/default_lb/28/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_28.json
python xview2_metrics.py val_scoring/default_lb/29/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_29.json
python xview2_metrics.py val_scoring/default_lb/30/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_30.json
python xview2_metrics.py val_scoring/default_lb/31/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_31.json
python xview2_metrics.py val_scoring/default_lb/32/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_32.json
python xview2_metrics.py val_scoring/default_lb/33/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_33.json
python xview2_metrics.py val_scoring/default_lb/34/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_34.json
python xview2_metrics.py val_scoring/default_lb/35/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_35.json
python xview2_metrics.py val_scoring/default_lb/36/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_36.json
python xview2_metrics.py val_scoring/default_lb/37/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_37.json
python xview2_metrics.py val_scoring/default_lb/38/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_38.json
python xview2_metrics.py val_scoring/default_lb/39/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_39.json
python xview2_metrics.py val_scoring/default_lb/40/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_40.json
python xview2_metrics.py val_scoring/default_lb/41/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_41.json
python xview2_metrics.py val_scoring/default_lb/42/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_42.json
python xview2_metrics.py val_scoring/default_lb/43/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_43.json
python xview2_metrics.py val_scoring/default_lb/44/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_44.json
python xview2_metrics.py val_scoring/default_lb/45/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_45.json
python xview2_metrics.py val_scoring/default_lb/46/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_46.json
python xview2_metrics.py val_scoring/default_lb/47/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_47.json
python xview2_metrics.py val_scoring/default_lb/48/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_48.json
python xview2_metrics.py val_scoring/default_lb/49/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_49.json
python xview2_metrics.py val_scoring/default_lb/50/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_50.json
python xview2_metrics.py val_scoring/default_lb/51/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_51.json
python xview2_metrics.py val_scoring/default_lb/52/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_52.json
python xview2_metrics.py val_scoring/default_lb/53/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_53.json
python xview2_metrics.py val_scoring/default_lb/54/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_54.json
python xview2_metrics.py val_scoring/default_lb/55/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_55.json
python xview2_metrics.py val_scoring/default_lb/56/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_56.json
python xview2_metrics.py val_scoring/default_lb/57/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_57.json
python xview2_metrics.py val_scoring/default_lb/58/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_58.json
python xview2_metrics.py val_scoring/default_lb/59/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_59.json
python xview2_metrics.py val_scoring/default_lb/60/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_60.json
python xview2_metrics.py val_scoring/default_lb/61/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_61.json
python xview2_metrics.py val_scoring/default_lb/62/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_62.json
python xview2_metrics.py val_scoring/default_lb/63/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_63.json
python xview2_metrics.py val_scoring/default_lb/64/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_64.json
python xview2_metrics.py val_scoring/default_lb/65/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_65.json
python xview2_metrics.py val_scoring/default_lb/66/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_66.json
python xview2_metrics.py val_scoring/default_lb/67/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_67.json
python xview2_metrics.py val_scoring/default_lb/68/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_68.json
python xview2_metrics.py val_scoring/default_lb/69/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_69.json
python xview2_metrics.py val_scoring/default_lb/70/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_70.json
python xview2_metrics.py val_scoring/default_lb/71/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_71.json
python xview2_metrics.py val_scoring/default_lb/72/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_72.json
python xview2_metrics.py val_scoring/default_lb/73/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_73.json
python xview2_metrics.py val_scoring/default_lb/74/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_74.json
python xview2_metrics.py val_scoring/default_lb/75/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_75.json
python xview2_metrics.py val_scoring/default_lb/76/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_76.json
python xview2_metrics.py val_scoring/default_lb/77/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_77.json
python xview2_metrics.py val_scoring/default_lb/78/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_78.json
python xview2_metrics.py val_scoring/default_lb/79/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_79.json
python xview2_metrics.py val_scoring/default_lb/80/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_80.json
python xview2_metrics.py val_scoring/default_lb/81/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_81.json
python xview2_metrics.py val_scoring/default_lb/82/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_82.json
python xview2_metrics.py val_scoring/default_lb/83/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_83.json
python xview2_metrics.py val_scoring/default_lb/84/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_84.json
python xview2_metrics.py val_scoring/default_lb/85/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_85.json
python xview2_metrics.py val_scoring/default_lb/86/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_86.json
python xview2_metrics.py val_scoring/default_lb/87/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_87.json
python xview2_metrics.py val_scoring/default_lb/88/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_88.json
python xview2_metrics.py val_scoring/default_lb/89/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_89.json
python xview2_metrics.py val_scoring/default_lb/90/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_90.json
python xview2_metrics.py val_scoring/default_lb/91/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_91.json
python xview2_metrics.py val_scoring/default_lb/92/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_92.json
python xview2_metrics.py val_scoring/default_lb/93/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_93.json
python xview2_metrics.py val_scoring/default_lb/94/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_94.json
python xview2_metrics.py val_scoring/default_lb/95/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_95.json
python xview2_metrics.py val_scoring/default_lb/96/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_96.json
python xview2_metrics.py val_scoring/default_lb/97/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_97.json
python xview2_metrics.py val_scoring/default_lb/98/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_98.json
python xview2_metrics.py val_scoring/default_lb/99/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_99.json
python xview2_metrics.py val_scoring/default_lb/100/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_100.json
python xview2_metrics.py val_scoring/default_lb/101/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_101.json
python xview2_metrics.py val_scoring/default_lb/102/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_102.json
python xview2_metrics.py val_scoring/default_lb/103/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_103.json
python xview2_metrics.py val_scoring/default_lb/104/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_104.json
python xview2_metrics.py val_scoring/default_lb/105/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_105.json
python xview2_metrics.py val_scoring/default_lb/106/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_106.json
python xview2_metrics.py val_scoring/default_lb/107/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_107.json
python xview2_metrics.py val_scoring/default_lb/108/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_108.json
python xview2_metrics.py val_scoring/default_lb/109/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_109.json
python xview2_metrics.py val_scoring/default_lb/110/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_110.json
python xview2_metrics.py val_scoring/default_lb/111/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_111.json
python xview2_metrics.py val_scoring/default_lb/112/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_112.json
python xview2_metrics.py val_scoring/default_lb/113/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_113.json
python xview2_metrics.py val_scoring/default_lb/114/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_114.json
python xview2_metrics.py val_scoring/default_lb/115/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_115.json
python xview2_metrics.py val_scoring/default_lb/116/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_116.json
python xview2_metrics.py val_scoring/default_lb/117/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_117.json
python xview2_metrics.py val_scoring/default_lb/118/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_118.json
python xview2_metrics.py val_scoring/default_lb/119/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_119.json
python xview2_metrics.py val_scoring/default_lb/120/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_120.json
python xview2_metrics.py val_scoring/default_lb/121/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_121.json
python xview2_metrics.py val_scoring/default_lb/122/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_122.json
python xview2_metrics.py val_scoring/default_lb/123/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_123.json
python xview2_metrics.py val_scoring/default_lb/124/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_124.json
python xview2_metrics.py val_scoring/default_lb/125/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_125.json
python xview2_metrics.py val_scoring/default_lb/126/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_126.json
python xview2_metrics.py val_scoring/default_lb/127/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_127.json
python xview2_metrics.py val_scoring/default_lb/128/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_128.json
python xview2_metrics.py val_scoring/default_lb/129/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_129.json
python xview2_metrics.py val_scoring/default_lb/130/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_130.json
python xview2_metrics.py val_scoring/default_lb/131/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_131.json
python xview2_metrics.py val_scoring/default_lb/132/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_132.json
python xview2_metrics.py val_scoring/default_lb/133/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_133.json
python xview2_metrics.py val_scoring/default_lb/134/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_134.json
python xview2_metrics.py val_scoring/default_lb/135/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_135.json
python xview2_metrics.py val_scoring/default_lb/136/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_136.json
python xview2_metrics.py val_scoring/default_lb/137/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_137.json
python xview2_metrics.py val_scoring/default_lb/138/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_138.json
python xview2_metrics.py val_scoring/default_lb/139/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_139.json
python xview2_metrics.py val_scoring/default_lb/140/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_140.json
python xview2_metrics.py val_scoring/default_lb/141/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_141.json
python xview2_metrics.py val_scoring/default_lb/142/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_142.json
python xview2_metrics.py val_scoring/default_lb/143/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_143.json
python xview2_metrics.py val_scoring/default_lb/144/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_144.json
python xview2_metrics.py val_scoring/default_lb/145/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_145.json
python xview2_metrics.py val_scoring/default_lb/146/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_146.json
python xview2_metrics.py val_scoring/default_lb/147/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_147.json
python xview2_metrics.py val_scoring/default_lb/148/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_148.json
python xview2_metrics.py val_scoring/default_lb/149/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_149.json
python xview2_metrics.py val_scoring/default_lb/150/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_150.json
python xview2_metrics.py val_scoring/default_lb/151/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_151.json
python xview2_metrics.py val_scoring/default_lb/152/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_152.json
python xview2_metrics.py val_scoring/default_lb/153/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_153.json
python xview2_metrics.py val_scoring/default_lb/154/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_154.json
python xview2_metrics.py val_scoring/default_lb/155/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_155.json
python xview2_metrics.py val_scoring/default_lb/156/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_156.json
python xview2_metrics.py val_scoring/default_lb/157/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_157.json
python xview2_metrics.py val_scoring/default_lb/158/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_158.json
python xview2_metrics.py val_scoring/default_lb/159/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_159.json
python xview2_metrics.py val_scoring/default_lb/160/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_160.json
python xview2_metrics.py val_scoring/default_lb/161/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_161.json
python xview2_metrics.py val_scoring/default_lb/162/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_162.json
python xview2_metrics.py val_scoring/default_lb/163/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_163.json
python xview2_metrics.py val_scoring/default_lb/164/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_164.json
python xview2_metrics.py val_scoring/default_lb/165/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_165.json
python xview2_metrics.py val_scoring/default_lb/166/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_166.json
python xview2_metrics.py val_scoring/default_lb/167/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_167.json
python xview2_metrics.py val_scoring/default_lb/168/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_168.json
python xview2_metrics.py val_scoring/default_lb/169/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_169.json
python xview2_metrics.py val_scoring/default_lb/170/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_170.json
python xview2_metrics.py val_scoring/default_lb/171/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_171.json
python xview2_metrics.py val_scoring/default_lb/172/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_172.json
python xview2_metrics.py val_scoring/default_lb/173/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_173.json
python xview2_metrics.py val_scoring/default_lb/174/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_174.json
python xview2_metrics.py val_scoring/default_lb/175/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_175.json
python xview2_metrics.py val_scoring/default_lb/176/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_176.json
python xview2_metrics.py val_scoring/default_lb/177/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_177.json
python xview2_metrics.py val_scoring/default_lb/178/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_178.json
python xview2_metrics.py val_scoring/default_lb/179/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_179.json
python xview2_metrics.py val_scoring/default_lb/180/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_180.json
python xview2_metrics.py val_scoring/default_lb/181/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_181.json
python xview2_metrics.py val_scoring/default_lb/182/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_182.json
python xview2_metrics.py val_scoring/default_lb/183/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_183.json
python xview2_metrics.py val_scoring/default_lb/184/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_184.json
python xview2_metrics.py val_scoring/default_lb/185/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_185.json
python xview2_metrics.py val_scoring/default_lb/186/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_186.json
python xview2_metrics.py val_scoring/default_lb/187/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_187.json
python xview2_metrics.py val_scoring/default_lb/188/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_188.json
python xview2_metrics.py val_scoring/default_lb/189/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_189.json
python xview2_metrics.py val_scoring/default_lb/190/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_190.json
python xview2_metrics.py val_scoring/default_lb/191/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_191.json
python xview2_metrics.py val_scoring/default_lb/192/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_192.json
python xview2_metrics.py val_scoring/default_lb/193/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_193.json
python xview2_metrics.py val_scoring/default_lb/194/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_194.json
python xview2_metrics.py val_scoring/default_lb/195/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_195.json
python xview2_metrics.py val_scoring/default_lb/196/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_196.json
python xview2_metrics.py val_scoring/default_lb/197/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_197.json
python xview2_metrics.py val_scoring/default_lb/198/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_198.json
python xview2_metrics.py val_scoring/default_lb/199/predictions/ val_scoring/default_lb/targets/ val_scores/default_lb/epoch_199.json
