python xview2_metrics.py val_scoring/\ 0/predictions/ val_scoring/\ 0/targets/ val_scores/epoch_0.json
python xview2_metrics.py val_scoring/\ 1/predictions/ val_scoring/\ 1/targets/ val_scores/epoch_1.json
python xview2_metrics.py val_scoring/\ 2/predictions/ val_scoring/\ 2/targets/ val_scores/epoch_2.json
python xview2_metrics.py val_scoring/\ 3/predictions/ val_scoring/\ 3/targets/ val_scores/epoch_3.json
python xview2_metrics.py val_scoring/\ 4/predictions/ val_scoring/\ 4/targets/ val_scores/epoch_4.json
python xview2_metrics.py val_scoring/\ 5/predictions/ val_scoring/\ 5/targets/ val_scores/epoch_5.json
python xview2_metrics.py val_scoring/\ 6/predictions/ val_scoring/\ 6/targets/ val_scores/epoch_6.json
python xview2_metrics.py val_scoring/\ 7/predictions/ val_scoring/\ 7/targets/ val_scores/epoch_7.json
python xview2_metrics.py val_scoring/\ 8/predictions/ val_scoring/\ 8/targets/ val_scores/epoch_8.json
python xview2_metrics.py val_scoring/\ 9/predictions/ val_scoring/\ 9/targets/ val_scores/epoch_9.json
python xview2_metrics.py val_scoring/\ 10/predictions/ val_scoring/\ 10/targets/ val_scores/epoch_10.json
python xview2_metrics.py val_scoring/\ 11/predictions/ val_scoring/\ 11/targets/ val_scores/epoch_11.json
python xview2_metrics.py val_scoring/\ 12/predictions/ val_scoring/\ 12/targets/ val_scores/epoch_12.json
python xview2_metrics.py val_scoring/\ 13/predictions/ val_scoring/\ 13/targets/ val_scores/epoch_13.json
python xview2_metrics.py val_scoring/\ 14/predictions/ val_scoring/\ 14/targets/ val_scores/epoch_14.json
python xview2_metrics.py val_scoring/\ 15/predictions/ val_scoring/\ 15/targets/ val_scores/epoch_15.json
python xview2_metrics.py val_scoring/\ 16/predictions/ val_scoring/\ 16/targets/ val_scores/epoch_16.json
python xview2_metrics.py val_scoring/\ 17/predictions/ val_scoring/\ 17/targets/ val_scores/epoch_17.json
python xview2_metrics.py val_scoring/\ 18/predictions/ val_scoring/\ 18/targets/ val_scores/epoch_18.json
python xview2_metrics.py val_scoring/\ 19/predictions/ val_scoring/\ 19/targets/ val_scores/epoch_19.json
python xview2_metrics.py val_scoring/\ 20/predictions/ val_scoring/\ 20/targets/ val_scores/epoch_20.json
python xview2_metrics.py val_scoring/\ 21/predictions/ val_scoring/\ 21/targets/ val_scores/epoch_21.json
python xview2_metrics.py val_scoring/\ 22/predictions/ val_scoring/\ 22/targets/ val_scores/epoch_22.json
python xview2_metrics.py val_scoring/\ 23/predictions/ val_scoring/\ 23/targets/ val_scores/epoch_23.json
python xview2_metrics.py val_scoring/\ 24/predictions/ val_scoring/\ 24/targets/ val_scores/epoch_24.json
python xview2_metrics.py val_scoring/\ 25/predictions/ val_scoring/\ 25/targets/ val_scores/epoch_25.json
python xview2_metrics.py val_scoring/\ 26/predictions/ val_scoring/\ 26/targets/ val_scores/epoch_26.json
python xview2_metrics.py val_scoring/\ 27/predictions/ val_scoring/\ 27/targets/ val_scores/epoch_27.json
python xview2_metrics.py val_scoring/\ 28/predictions/ val_scoring/\ 28/targets/ val_scores/epoch_28.json
python xview2_metrics.py val_scoring/\ 29/predictions/ val_scoring/\ 29/targets/ val_scores/epoch_29.json
python xview2_metrics.py val_scoring/\ 30/predictions/ val_scoring/\ 30/targets/ val_scores/epoch_30.json
python xview2_metrics.py val_scoring/\ 31/predictions/ val_scoring/\ 31/targets/ val_scores/epoch_31.json
python xview2_metrics.py val_scoring/\ 32/predictions/ val_scoring/\ 32/targets/ val_scores/epoch_32.json
python xview2_metrics.py val_scoring/\ 33/predictions/ val_scoring/\ 33/targets/ val_scores/epoch_33.json
python xview2_metrics.py val_scoring/\ 34/predictions/ val_scoring/\ 34/targets/ val_scores/epoch_34.json
python xview2_metrics.py val_scoring/\ 35/predictions/ val_scoring/\ 35/targets/ val_scores/epoch_35.json
python xview2_metrics.py val_scoring/\ 36/predictions/ val_scoring/\ 36/targets/ val_scores/epoch_36.json
python xview2_metrics.py val_scoring/\ 37/predictions/ val_scoring/\ 37/targets/ val_scores/epoch_37.json
python xview2_metrics.py val_scoring/\ 38/predictions/ val_scoring/\ 38/targets/ val_scores/epoch_38.json
python xview2_metrics.py val_scoring/\ 39/predictions/ val_scoring/\ 39/targets/ val_scores/epoch_39.json
python xview2_metrics.py val_scoring/\ 40/predictions/ val_scoring/\ 40/targets/ val_scores/epoch_40.json
python xview2_metrics.py val_scoring/\ 41/predictions/ val_scoring/\ 41/targets/ val_scores/epoch_41.json
python xview2_metrics.py val_scoring/\ 42/predictions/ val_scoring/\ 42/targets/ val_scores/epoch_42.json
python xview2_metrics.py val_scoring/\ 43/predictions/ val_scoring/\ 43/targets/ val_scores/epoch_43.json
python xview2_metrics.py val_scoring/\ 44/predictions/ val_scoring/\ 44/targets/ val_scores/epoch_44.json
python xview2_metrics.py val_scoring/\ 45/predictions/ val_scoring/\ 45/targets/ val_scores/epoch_45.json
python xview2_metrics.py val_scoring/\ 46/predictions/ val_scoring/\ 46/targets/ val_scores/epoch_46.json
python xview2_metrics.py val_scoring/\ 47/predictions/ val_scoring/\ 47/targets/ val_scores/epoch_47.json
python xview2_metrics.py val_scoring/\ 48/predictions/ val_scoring/\ 48/targets/ val_scores/epoch_48.json
python xview2_metrics.py val_scoring/\ 49/predictions/ val_scoring/\ 49/targets/ val_scores/epoch_49.json
python xview2_metrics.py val_scoring/\ 50/predictions/ val_scoring/\ 50/targets/ val_scores/epoch_50.json
python xview2_metrics.py val_scoring/\ 51/predictions/ val_scoring/\ 51/targets/ val_scores/epoch_51.json
python xview2_metrics.py val_scoring/\ 52/predictions/ val_scoring/\ 52/targets/ val_scores/epoch_52.json
python xview2_metrics.py val_scoring/\ 53/predictions/ val_scoring/\ 53/targets/ val_scores/epoch_53.json
python xview2_metrics.py val_scoring/\ 54/predictions/ val_scoring/\ 54/targets/ val_scores/epoch_54.json
python xview2_metrics.py val_scoring/\ 55/predictions/ val_scoring/\ 55/targets/ val_scores/epoch_55.json
python xview2_metrics.py val_scoring/\ 56/predictions/ val_scoring/\ 56/targets/ val_scores/epoch_56.json
python xview2_metrics.py val_scoring/\ 57/predictions/ val_scoring/\ 57/targets/ val_scores/epoch_57.json
python xview2_metrics.py val_scoring/\ 58/predictions/ val_scoring/\ 58/targets/ val_scores/epoch_58.json
python xview2_metrics.py val_scoring/\ 59/predictions/ val_scoring/\ 59/targets/ val_scores/epoch_59.json
python xview2_metrics.py val_scoring/\ 60/predictions/ val_scoring/\ 60/targets/ val_scores/epoch_60.json
python xview2_metrics.py val_scoring/\ 61/predictions/ val_scoring/\ 61/targets/ val_scores/epoch_61.json
python xview2_metrics.py val_scoring/\ 62/predictions/ val_scoring/\ 62/targets/ val_scores/epoch_62.json
python xview2_metrics.py val_scoring/\ 63/predictions/ val_scoring/\ 63/targets/ val_scores/epoch_63.json
python xview2_metrics.py val_scoring/\ 64/predictions/ val_scoring/\ 64/targets/ val_scores/epoch_64.json
python xview2_metrics.py val_scoring/\ 65/predictions/ val_scoring/\ 65/targets/ val_scores/epoch_65.json
python xview2_metrics.py val_scoring/\ 66/predictions/ val_scoring/\ 66/targets/ val_scores/epoch_66.json
python xview2_metrics.py val_scoring/\ 67/predictions/ val_scoring/\ 67/targets/ val_scores/epoch_67.json
python xview2_metrics.py val_scoring/\ 68/predictions/ val_scoring/\ 68/targets/ val_scores/epoch_68.json
python xview2_metrics.py val_scoring/\ 69/predictions/ val_scoring/\ 69/targets/ val_scores/epoch_69.json
python xview2_metrics.py val_scoring/\ 70/predictions/ val_scoring/\ 70/targets/ val_scores/epoch_70.json
python xview2_metrics.py val_scoring/\ 71/predictions/ val_scoring/\ 71/targets/ val_scores/epoch_71.json
python xview2_metrics.py val_scoring/\ 72/predictions/ val_scoring/\ 72/targets/ val_scores/epoch_72.json
python xview2_metrics.py val_scoring/\ 73/predictions/ val_scoring/\ 73/targets/ val_scores/epoch_73.json
python xview2_metrics.py val_scoring/\ 74/predictions/ val_scoring/\ 74/targets/ val_scores/epoch_74.json
python xview2_metrics.py val_scoring/\ 75/predictions/ val_scoring/\ 75/targets/ val_scores/epoch_75.json
python xview2_metrics.py val_scoring/\ 76/predictions/ val_scoring/\ 76/targets/ val_scores/epoch_76.json
python xview2_metrics.py val_scoring/\ 77/predictions/ val_scoring/\ 77/targets/ val_scores/epoch_77.json
python xview2_metrics.py val_scoring/\ 78/predictions/ val_scoring/\ 78/targets/ val_scores/epoch_78.json
python xview2_metrics.py val_scoring/\ 79/predictions/ val_scoring/\ 79/targets/ val_scores/epoch_79.json
python xview2_metrics.py val_scoring/\ 80/predictions/ val_scoring/\ 80/targets/ val_scores/epoch_80.json
python xview2_metrics.py val_scoring/\ 81/predictions/ val_scoring/\ 81/targets/ val_scores/epoch_81.json
python xview2_metrics.py val_scoring/\ 82/predictions/ val_scoring/\ 82/targets/ val_scores/epoch_82.json
python xview2_metrics.py val_scoring/\ 83/predictions/ val_scoring/\ 83/targets/ val_scores/epoch_83.json
python xview2_metrics.py val_scoring/\ 84/predictions/ val_scoring/\ 84/targets/ val_scores/epoch_84.json
python xview2_metrics.py val_scoring/\ 85/predictions/ val_scoring/\ 85/targets/ val_scores/epoch_85.json
python xview2_metrics.py val_scoring/\ 86/predictions/ val_scoring/\ 86/targets/ val_scores/epoch_86.json
python xview2_metrics.py val_scoring/\ 87/predictions/ val_scoring/\ 87/targets/ val_scores/epoch_87.json
python xview2_metrics.py val_scoring/\ 88/predictions/ val_scoring/\ 88/targets/ val_scores/epoch_88.json
python xview2_metrics.py val_scoring/\ 89/predictions/ val_scoring/\ 89/targets/ val_scores/epoch_89.json
python xview2_metrics.py val_scoring/\ 90/predictions/ val_scoring/\ 90/targets/ val_scores/epoch_90.json
python xview2_metrics.py val_scoring/\ 91/predictions/ val_scoring/\ 91/targets/ val_scores/epoch_91.json
python xview2_metrics.py val_scoring/\ 92/predictions/ val_scoring/\ 92/targets/ val_scores/epoch_92.json
python xview2_metrics.py val_scoring/\ 93/predictions/ val_scoring/\ 93/targets/ val_scores/epoch_93.json
python xview2_metrics.py val_scoring/\ 94/predictions/ val_scoring/\ 94/targets/ val_scores/epoch_94.json
python xview2_metrics.py val_scoring/\ 95/predictions/ val_scoring/\ 95/targets/ val_scores/epoch_95.json
python xview2_metrics.py val_scoring/\ 96/predictions/ val_scoring/\ 96/targets/ val_scores/epoch_96.json
python xview2_metrics.py val_scoring/\ 97/predictions/ val_scoring/\ 97/targets/ val_scores/epoch_97.json
python xview2_metrics.py val_scoring/\ 98/predictions/ val_scoring/\ 98/targets/ val_scores/epoch_98.json
python xview2_metrics.py val_scoring/\ 99/predictions/ val_scoring/\ 99/targets/ val_scores/epoch_99.json
python xview2_metrics.py val_scoring/\ 100/predictions/ val_scoring/\ 100/targets/ val_scores/epoch_100.json
python xview2_metrics.py val_scoring/\ 101/predictions/ val_scoring/\ 101/targets/ val_scores/epoch_101.json
python xview2_metrics.py val_scoring/\ 102/predictions/ val_scoring/\ 102/targets/ val_scores/epoch_102.json
python xview2_metrics.py val_scoring/\ 103/predictions/ val_scoring/\ 103/targets/ val_scores/epoch_103.json
python xview2_metrics.py val_scoring/\ 104/predictions/ val_scoring/\ 104/targets/ val_scores/epoch_104.json
python xview2_metrics.py val_scoring/\ 105/predictions/ val_scoring/\ 105/targets/ val_scores/epoch_105.json
python xview2_metrics.py val_scoring/\ 106/predictions/ val_scoring/\ 106/targets/ val_scores/epoch_106.json
python xview2_metrics.py val_scoring/\ 107/predictions/ val_scoring/\ 107/targets/ val_scores/epoch_107.json
python xview2_metrics.py val_scoring/\ 108/predictions/ val_scoring/\ 108/targets/ val_scores/epoch_108.json
python xview2_metrics.py val_scoring/\ 109/predictions/ val_scoring/\ 109/targets/ val_scores/epoch_109.json
python xview2_metrics.py val_scoring/\ 110/predictions/ val_scoring/\ 110/targets/ val_scores/epoch_110.json
python xview2_metrics.py val_scoring/\ 111/predictions/ val_scoring/\ 111/targets/ val_scores/epoch_111.json
python xview2_metrics.py val_scoring/\ 112/predictions/ val_scoring/\ 112/targets/ val_scores/epoch_112.json
python xview2_metrics.py val_scoring/\ 113/predictions/ val_scoring/\ 113/targets/ val_scores/epoch_113.json
python xview2_metrics.py val_scoring/\ 114/predictions/ val_scoring/\ 114/targets/ val_scores/epoch_114.json
python xview2_metrics.py val_scoring/\ 115/predictions/ val_scoring/\ 115/targets/ val_scores/epoch_115.json
python xview2_metrics.py val_scoring/\ 116/predictions/ val_scoring/\ 116/targets/ val_scores/epoch_116.json
python xview2_metrics.py val_scoring/\ 117/predictions/ val_scoring/\ 117/targets/ val_scores/epoch_117.json
python xview2_metrics.py val_scoring/\ 118/predictions/ val_scoring/\ 118/targets/ val_scores/epoch_118.json
python xview2_metrics.py val_scoring/\ 119/predictions/ val_scoring/\ 119/targets/ val_scores/epoch_119.json
python xview2_metrics.py val_scoring/\ 120/predictions/ val_scoring/\ 120/targets/ val_scores/epoch_120.json
python xview2_metrics.py val_scoring/\ 121/predictions/ val_scoring/\ 121/targets/ val_scores/epoch_121.json
python xview2_metrics.py val_scoring/\ 122/predictions/ val_scoring/\ 122/targets/ val_scores/epoch_122.json
python xview2_metrics.py val_scoring/\ 123/predictions/ val_scoring/\ 123/targets/ val_scores/epoch_123.json
python xview2_metrics.py val_scoring/\ 124/predictions/ val_scoring/\ 124/targets/ val_scores/epoch_124.json
python xview2_metrics.py val_scoring/\ 125/predictions/ val_scoring/\ 125/targets/ val_scores/epoch_125.json
python xview2_metrics.py val_scoring/\ 126/predictions/ val_scoring/\ 126/targets/ val_scores/epoch_126.json
python xview2_metrics.py val_scoring/\ 127/predictions/ val_scoring/\ 127/targets/ val_scores/epoch_127.json
python xview2_metrics.py val_scoring/\ 128/predictions/ val_scoring/\ 128/targets/ val_scores/epoch_128.json
python xview2_metrics.py val_scoring/\ 129/predictions/ val_scoring/\ 129/targets/ val_scores/epoch_129.json
python xview2_metrics.py val_scoring/\ 130/predictions/ val_scoring/\ 130/targets/ val_scores/epoch_130.json
python xview2_metrics.py val_scoring/\ 131/predictions/ val_scoring/\ 131/targets/ val_scores/epoch_131.json
python xview2_metrics.py val_scoring/\ 132/predictions/ val_scoring/\ 132/targets/ val_scores/epoch_132.json
python xview2_metrics.py val_scoring/\ 133/predictions/ val_scoring/\ 133/targets/ val_scores/epoch_133.json
python xview2_metrics.py val_scoring/\ 134/predictions/ val_scoring/\ 134/targets/ val_scores/epoch_134.json
python xview2_metrics.py val_scoring/\ 135/predictions/ val_scoring/\ 135/targets/ val_scores/epoch_135.json
python xview2_metrics.py val_scoring/\ 136/predictions/ val_scoring/\ 136/targets/ val_scores/epoch_136.json
python xview2_metrics.py val_scoring/\ 137/predictions/ val_scoring/\ 137/targets/ val_scores/epoch_137.json
python xview2_metrics.py val_scoring/\ 138/predictions/ val_scoring/\ 138/targets/ val_scores/epoch_138.json
python xview2_metrics.py val_scoring/\ 139/predictions/ val_scoring/\ 139/targets/ val_scores/epoch_139.json
python xview2_metrics.py val_scoring/\ 140/predictions/ val_scoring/\ 140/targets/ val_scores/epoch_140.json
python xview2_metrics.py val_scoring/\ 141/predictions/ val_scoring/\ 141/targets/ val_scores/epoch_141.json
python xview2_metrics.py val_scoring/\ 142/predictions/ val_scoring/\ 142/targets/ val_scores/epoch_142.json
python xview2_metrics.py val_scoring/\ 143/predictions/ val_scoring/\ 143/targets/ val_scores/epoch_143.json
python xview2_metrics.py val_scoring/\ 144/predictions/ val_scoring/\ 144/targets/ val_scores/epoch_144.json
python xview2_metrics.py val_scoring/\ 145/predictions/ val_scoring/\ 145/targets/ val_scores/epoch_145.json
python xview2_metrics.py val_scoring/\ 146/predictions/ val_scoring/\ 146/targets/ val_scores/epoch_146.json
python xview2_metrics.py val_scoring/\ 147/predictions/ val_scoring/\ 147/targets/ val_scores/epoch_147.json
python xview2_metrics.py val_scoring/\ 148/predictions/ val_scoring/\ 148/targets/ val_scores/epoch_148.json
python xview2_metrics.py val_scoring/\ 149/predictions/ val_scoring/\ 149/targets/ val_scores/epoch_149.json
python xview2_metrics.py val_scoring/\ 150/predictions/ val_scoring/\ 150/targets/ val_scores/epoch_150.json
python xview2_metrics.py val_scoring/\ 151/predictions/ val_scoring/\ 151/targets/ val_scores/epoch_151.json
python xview2_metrics.py val_scoring/\ 152/predictions/ val_scoring/\ 152/targets/ val_scores/epoch_152.json
python xview2_metrics.py val_scoring/\ 153/predictions/ val_scoring/\ 153/targets/ val_scores/epoch_153.json
python xview2_metrics.py val_scoring/\ 154/predictions/ val_scoring/\ 154/targets/ val_scores/epoch_154.json
python xview2_metrics.py val_scoring/\ 155/predictions/ val_scoring/\ 155/targets/ val_scores/epoch_155.json
python xview2_metrics.py val_scoring/\ 156/predictions/ val_scoring/\ 156/targets/ val_scores/epoch_156.json
python xview2_metrics.py val_scoring/\ 157/predictions/ val_scoring/\ 157/targets/ val_scores/epoch_157.json
python xview2_metrics.py val_scoring/\ 158/predictions/ val_scoring/\ 158/targets/ val_scores/epoch_158.json
python xview2_metrics.py val_scoring/\ 159/predictions/ val_scoring/\ 159/targets/ val_scores/epoch_159.json
python xview2_metrics.py val_scoring/\ 160/predictions/ val_scoring/\ 160/targets/ val_scores/epoch_160.json
python xview2_metrics.py val_scoring/\ 161/predictions/ val_scoring/\ 161/targets/ val_scores/epoch_161.json
python xview2_metrics.py val_scoring/\ 162/predictions/ val_scoring/\ 162/targets/ val_scores/epoch_162.json
python xview2_metrics.py val_scoring/\ 163/predictions/ val_scoring/\ 163/targets/ val_scores/epoch_163.json
python xview2_metrics.py val_scoring/\ 164/predictions/ val_scoring/\ 164/targets/ val_scores/epoch_164.json
python xview2_metrics.py val_scoring/\ 165/predictions/ val_scoring/\ 165/targets/ val_scores/epoch_165.json
python xview2_metrics.py val_scoring/\ 166/predictions/ val_scoring/\ 166/targets/ val_scores/epoch_166.json
python xview2_metrics.py val_scoring/\ 167/predictions/ val_scoring/\ 167/targets/ val_scores/epoch_167.json
python xview2_metrics.py val_scoring/\ 168/predictions/ val_scoring/\ 168/targets/ val_scores/epoch_168.json
python xview2_metrics.py val_scoring/\ 169/predictions/ val_scoring/\ 169/targets/ val_scores/epoch_169.json
python xview2_metrics.py val_scoring/\ 170/predictions/ val_scoring/\ 170/targets/ val_scores/epoch_170.json
python xview2_metrics.py val_scoring/\ 171/predictions/ val_scoring/\ 171/targets/ val_scores/epoch_171.json
python xview2_metrics.py val_scoring/\ 172/predictions/ val_scoring/\ 172/targets/ val_scores/epoch_172.json
python xview2_metrics.py val_scoring/\ 173/predictions/ val_scoring/\ 173/targets/ val_scores/epoch_173.json
python xview2_metrics.py val_scoring/\ 174/predictions/ val_scoring/\ 174/targets/ val_scores/epoch_174.json
python xview2_metrics.py val_scoring/\ 175/predictions/ val_scoring/\ 175/targets/ val_scores/epoch_175.json
python xview2_metrics.py val_scoring/\ 176/predictions/ val_scoring/\ 176/targets/ val_scores/epoch_176.json
python xview2_metrics.py val_scoring/\ 177/predictions/ val_scoring/\ 177/targets/ val_scores/epoch_177.json
python xview2_metrics.py val_scoring/\ 178/predictions/ val_scoring/\ 178/targets/ val_scores/epoch_178.json
python xview2_metrics.py val_scoring/\ 179/predictions/ val_scoring/\ 179/targets/ val_scores/epoch_179.json
python xview2_metrics.py val_scoring/\ 180/predictions/ val_scoring/\ 180/targets/ val_scores/epoch_180.json
python xview2_metrics.py val_scoring/\ 181/predictions/ val_scoring/\ 181/targets/ val_scores/epoch_181.json
python xview2_metrics.py val_scoring/\ 182/predictions/ val_scoring/\ 182/targets/ val_scores/epoch_182.json
python xview2_metrics.py val_scoring/\ 183/predictions/ val_scoring/\ 183/targets/ val_scores/epoch_183.json
python xview2_metrics.py val_scoring/\ 184/predictions/ val_scoring/\ 184/targets/ val_scores/epoch_184.json
python xview2_metrics.py val_scoring/\ 185/predictions/ val_scoring/\ 185/targets/ val_scores/epoch_185.json
python xview2_metrics.py val_scoring/\ 186/predictions/ val_scoring/\ 186/targets/ val_scores/epoch_186.json
python xview2_metrics.py val_scoring/\ 187/predictions/ val_scoring/\ 187/targets/ val_scores/epoch_187.json
python xview2_metrics.py val_scoring/\ 188/predictions/ val_scoring/\ 188/targets/ val_scores/epoch_188.json
python xview2_metrics.py val_scoring/\ 189/predictions/ val_scoring/\ 189/targets/ val_scores/epoch_189.json
python xview2_metrics.py val_scoring/\ 190/predictions/ val_scoring/\ 190/targets/ val_scores/epoch_190.json
python xview2_metrics.py val_scoring/\ 191/predictions/ val_scoring/\ 191/targets/ val_scores/epoch_191.json
python xview2_metrics.py val_scoring/\ 192/predictions/ val_scoring/\ 192/targets/ val_scores/epoch_192.json
python xview2_metrics.py val_scoring/\ 193/predictions/ val_scoring/\ 193/targets/ val_scores/epoch_193.json
python xview2_metrics.py val_scoring/\ 194/predictions/ val_scoring/\ 194/targets/ val_scores/epoch_194.json
python xview2_metrics.py val_scoring/\ 195/predictions/ val_scoring/\ 195/targets/ val_scores/epoch_195.json
python xview2_metrics.py val_scoring/\ 196/predictions/ val_scoring/\ 196/targets/ val_scores/epoch_196.json
python xview2_metrics.py val_scoring/\ 197/predictions/ val_scoring/\ 197/targets/ val_scores/epoch_197.json
python xview2_metrics.py val_scoring/\ 198/predictions/ val_scoring/\ 198/targets/ val_scores/epoch_198.json
python xview2_metrics.py val_scoring/\ 199/predictions/ val_scoring/\ 199/targets/ val_scores/epoch_199.json
