python xview2_metrics.py scoring/\ 0/predictions/ scoring/\ 0/targets/ scores/sample_score_e0.json
python xview2_metrics.py scoring/\ 1/predictions/ scoring/\ 1/targets/ scores/sample_score_e1.json
python xview2_metrics.py scoring/\ 2/predictions/ scoring/\ 2/targets/ scores/sample_score_e2.json
python xview2_metrics.py scoring/\ 3/predictions/ scoring/\ 3/targets/ scores/sample_score_e3.json
python xview2_metrics.py scoring/\ 4/predictions/ scoring/\ 4/targets/ scores/sample_score_e4.json
python xview2_metrics.py scoring/\ 5/predictions/ scoring/\ 5/targets/ scores/sample_score_e5.json
python xview2_metrics.py scoring/\ 6/predictions/ scoring/\ 6/targets/ scores/sample_score_e6.json
python xview2_metrics.py scoring/\ 7/predictions/ scoring/\ 7/targets/ scores/sample_score_e7.json
python xview2_metrics.py scoring/\ 8/predictions/ scoring/\ 8/targets/ scores/sample_score_e8.json
python xview2_metrics.py scoring/\ 9/predictions/ scoring/\ 9/targets/ scores/sample_score_e9.json
python xview2_metrics.py scoring/\ 10/predictions/ scoring/\ 10/targets/ scores/sample_score_e10.json
python xview2_metrics.py scoring/\ 11/predictions/ scoring/\ 11/targets/ scores/sample_score_e11.json
python xview2_metrics.py scoring/\ 12/predictions/ scoring/\ 12/targets/ scores/sample_score_e12.json
python xview2_metrics.py scoring/\ 13/predictions/ scoring/\ 13/targets/ scores/sample_score_e13.json
python xview2_metrics.py scoring/\ 14/predictions/ scoring/\ 14/targets/ scores/sample_score_e14.json
python xview2_metrics.py scoring/\ 15/predictions/ scoring/\ 15/targets/ scores/sample_score_e15.json
python xview2_metrics.py scoring/\ 16/predictions/ scoring/\ 16/targets/ scores/sample_score_e16.json
python xview2_metrics.py scoring/\ 17/predictions/ scoring/\ 17/targets/ scores/sample_score_e17.json
python xview2_metrics.py scoring/\ 18/predictions/ scoring/\ 18/targets/ scores/sample_score_e18.json
python xview2_metrics.py scoring/\ 19/predictions/ scoring/\ 19/targets/ scores/sample_score_e19.json
python xview2_metrics.py scoring/\ 20/predictions/ scoring/\ 20/targets/ scores/sample_score_e20.json
python xview2_metrics.py scoring/\ 21/predictions/ scoring/\ 21/targets/ scores/sample_score_e21.json
python xview2_metrics.py scoring/\ 22/predictions/ scoring/\ 22/targets/ scores/sample_score_e22.json
python xview2_metrics.py scoring/\ 23/predictions/ scoring/\ 23/targets/ scores/sample_score_e23.json
python xview2_metrics.py scoring/\ 24/predictions/ scoring/\ 24/targets/ scores/sample_score_e24.json
python xview2_metrics.py scoring/\ 25/predictions/ scoring/\ 25/targets/ scores/sample_score_e25.json
python xview2_metrics.py scoring/\ 26/predictions/ scoring/\ 26/targets/ scores/sample_score_e26.json
python xview2_metrics.py scoring/\ 27/predictions/ scoring/\ 27/targets/ scores/sample_score_e27.json
python xview2_metrics.py scoring/\ 28/predictions/ scoring/\ 28/targets/ scores/sample_score_e28.json
python xview2_metrics.py scoring/\ 29/predictions/ scoring/\ 29/targets/ scores/sample_score_e29.json
python xview2_metrics.py scoring/\ 30/predictions/ scoring/\ 30/targets/ scores/sample_score_e30.json
python xview2_metrics.py scoring/\ 31/predictions/ scoring/\ 31/targets/ scores/sample_score_e31.json
python xview2_metrics.py scoring/\ 32/predictions/ scoring/\ 32/targets/ scores/sample_score_e32.json
python xview2_metrics.py scoring/\ 33/predictions/ scoring/\ 33/targets/ scores/sample_score_e33.json
python xview2_metrics.py scoring/\ 34/predictions/ scoring/\ 34/targets/ scores/sample_score_e34.json
python xview2_metrics.py scoring/\ 35/predictions/ scoring/\ 35/targets/ scores/sample_score_e35.json
python xview2_metrics.py scoring/\ 36/predictions/ scoring/\ 36/targets/ scores/sample_score_e36.json
python xview2_metrics.py scoring/\ 37/predictions/ scoring/\ 37/targets/ scores/sample_score_e37.json
python xview2_metrics.py scoring/\ 38/predictions/ scoring/\ 38/targets/ scores/sample_score_e38.json
python xview2_metrics.py scoring/\ 39/predictions/ scoring/\ 39/targets/ scores/sample_score_e39.json
python xview2_metrics.py scoring/\ 40/predictions/ scoring/\ 40/targets/ scores/sample_score_e40.json
python xview2_metrics.py scoring/\ 41/predictions/ scoring/\ 41/targets/ scores/sample_score_e41.json
python xview2_metrics.py scoring/\ 42/predictions/ scoring/\ 42/targets/ scores/sample_score_e42.json
python xview2_metrics.py scoring/\ 43/predictions/ scoring/\ 43/targets/ scores/sample_score_e43.json
python xview2_metrics.py scoring/\ 44/predictions/ scoring/\ 44/targets/ scores/sample_score_e44.json
python xview2_metrics.py scoring/\ 45/predictions/ scoring/\ 45/targets/ scores/sample_score_e45.json
python xview2_metrics.py scoring/\ 46/predictions/ scoring/\ 46/targets/ scores/sample_score_e46.json
python xview2_metrics.py scoring/\ 47/predictions/ scoring/\ 47/targets/ scores/sample_score_e47.json
python xview2_metrics.py scoring/\ 48/predictions/ scoring/\ 48/targets/ scores/sample_score_e48.json
python xview2_metrics.py scoring/\ 49/predictions/ scoring/\ 49/targets/ scores/sample_score_e49.json
python xview2_metrics.py scoring/\ 50/predictions/ scoring/\ 50/targets/ scores/sample_score_e50.json
python xview2_metrics.py scoring/\ 51/predictions/ scoring/\ 51/targets/ scores/sample_score_e51.json
python xview2_metrics.py scoring/\ 52/predictions/ scoring/\ 52/targets/ scores/sample_score_e52.json
python xview2_metrics.py scoring/\ 53/predictions/ scoring/\ 53/targets/ scores/sample_score_e53.json
python xview2_metrics.py scoring/\ 54/predictions/ scoring/\ 54/targets/ scores/sample_score_e54.json
python xview2_metrics.py scoring/\ 55/predictions/ scoring/\ 55/targets/ scores/sample_score_e55.json
python xview2_metrics.py scoring/\ 56/predictions/ scoring/\ 56/targets/ scores/sample_score_e56.json
python xview2_metrics.py scoring/\ 57/predictions/ scoring/\ 57/targets/ scores/sample_score_e57.json
python xview2_metrics.py scoring/\ 58/predictions/ scoring/\ 58/targets/ scores/sample_score_e58.json
python xview2_metrics.py scoring/\ 59/predictions/ scoring/\ 59/targets/ scores/sample_score_e59.json
python xview2_metrics.py scoring/\ 60/predictions/ scoring/\ 60/targets/ scores/sample_score_e60.json
python xview2_metrics.py scoring/\ 61/predictions/ scoring/\ 61/targets/ scores/sample_score_e61.json
python xview2_metrics.py scoring/\ 62/predictions/ scoring/\ 62/targets/ scores/sample_score_e62.json
python xview2_metrics.py scoring/\ 63/predictions/ scoring/\ 63/targets/ scores/sample_score_e63.json
python xview2_metrics.py scoring/\ 64/predictions/ scoring/\ 64/targets/ scores/sample_score_e64.json
python xview2_metrics.py scoring/\ 65/predictions/ scoring/\ 65/targets/ scores/sample_score_e65.json
python xview2_metrics.py scoring/\ 66/predictions/ scoring/\ 66/targets/ scores/sample_score_e66.json
python xview2_metrics.py scoring/\ 67/predictions/ scoring/\ 67/targets/ scores/sample_score_e67.json
python xview2_metrics.py scoring/\ 68/predictions/ scoring/\ 68/targets/ scores/sample_score_e68.json
python xview2_metrics.py scoring/\ 69/predictions/ scoring/\ 69/targets/ scores/sample_score_e69.json
python xview2_metrics.py scoring/\ 70/predictions/ scoring/\ 70/targets/ scores/sample_score_e70.json
python xview2_metrics.py scoring/\ 71/predictions/ scoring/\ 71/targets/ scores/sample_score_e71.json
python xview2_metrics.py scoring/\ 72/predictions/ scoring/\ 72/targets/ scores/sample_score_e72.json
python xview2_metrics.py scoring/\ 73/predictions/ scoring/\ 73/targets/ scores/sample_score_e73.json
python xview2_metrics.py scoring/\ 74/predictions/ scoring/\ 74/targets/ scores/sample_score_e74.json
python xview2_metrics.py scoring/\ 75/predictions/ scoring/\ 75/targets/ scores/sample_score_e75.json
python xview2_metrics.py scoring/\ 76/predictions/ scoring/\ 76/targets/ scores/sample_score_e76.json
python xview2_metrics.py scoring/\ 77/predictions/ scoring/\ 77/targets/ scores/sample_score_e77.json
python xview2_metrics.py scoring/\ 78/predictions/ scoring/\ 78/targets/ scores/sample_score_e78.json
python xview2_metrics.py scoring/\ 79/predictions/ scoring/\ 79/targets/ scores/sample_score_e79.json
python xview2_metrics.py scoring/\ 80/predictions/ scoring/\ 80/targets/ scores/sample_score_e80.json
python xview2_metrics.py scoring/\ 81/predictions/ scoring/\ 81/targets/ scores/sample_score_e81.json
python xview2_metrics.py scoring/\ 82/predictions/ scoring/\ 82/targets/ scores/sample_score_e82.json
python xview2_metrics.py scoring/\ 83/predictions/ scoring/\ 83/targets/ scores/sample_score_e83.json
python xview2_metrics.py scoring/\ 84/predictions/ scoring/\ 84/targets/ scores/sample_score_e84.json
python xview2_metrics.py scoring/\ 85/predictions/ scoring/\ 85/targets/ scores/sample_score_e85.json
python xview2_metrics.py scoring/\ 86/predictions/ scoring/\ 86/targets/ scores/sample_score_e86.json
python xview2_metrics.py scoring/\ 87/predictions/ scoring/\ 87/targets/ scores/sample_score_e87.json
python xview2_metrics.py scoring/\ 88/predictions/ scoring/\ 88/targets/ scores/sample_score_e88.json
python xview2_metrics.py scoring/\ 89/predictions/ scoring/\ 89/targets/ scores/sample_score_e89.json
python xview2_metrics.py scoring/\ 90/predictions/ scoring/\ 90/targets/ scores/sample_score_e90.json
python xview2_metrics.py scoring/\ 91/predictions/ scoring/\ 91/targets/ scores/sample_score_e91.json
python xview2_metrics.py scoring/\ 92/predictions/ scoring/\ 92/targets/ scores/sample_score_e92.json
python xview2_metrics.py scoring/\ 93/predictions/ scoring/\ 93/targets/ scores/sample_score_e93.json
python xview2_metrics.py scoring/\ 94/predictions/ scoring/\ 94/targets/ scores/sample_score_e94.json
python xview2_metrics.py scoring/\ 95/predictions/ scoring/\ 95/targets/ scores/sample_score_e95.json
python xview2_metrics.py scoring/\ 96/predictions/ scoring/\ 96/targets/ scores/sample_score_e96.json
python xview2_metrics.py scoring/\ 97/predictions/ scoring/\ 97/targets/ scores/sample_score_e97.json
python xview2_metrics.py scoring/\ 98/predictions/ scoring/\ 98/targets/ scores/sample_score_e98.json
python xview2_metrics.py scoring/\ 99/predictions/ scoring/\ 99/targets/ scores/sample_score_e99.json
python xview2_metrics.py scoring/\ 100/predictions/ scoring/\ 100/targets/ scores/sample_score_e100.json
python xview2_metrics.py scoring/\ 101/predictions/ scoring/\ 101/targets/ scores/sample_score_e101.json
python xview2_metrics.py scoring/\ 102/predictions/ scoring/\ 102/targets/ scores/sample_score_e102.json
python xview2_metrics.py scoring/\ 103/predictions/ scoring/\ 103/targets/ scores/sample_score_e103.json
python xview2_metrics.py scoring/\ 104/predictions/ scoring/\ 104/targets/ scores/sample_score_e104.json
python xview2_metrics.py scoring/\ 105/predictions/ scoring/\ 105/targets/ scores/sample_score_e105.json
python xview2_metrics.py scoring/\ 106/predictions/ scoring/\ 106/targets/ scores/sample_score_e106.json
python xview2_metrics.py scoring/\ 107/predictions/ scoring/\ 107/targets/ scores/sample_score_e107.json
python xview2_metrics.py scoring/\ 108/predictions/ scoring/\ 108/targets/ scores/sample_score_e108.json
python xview2_metrics.py scoring/\ 109/predictions/ scoring/\ 109/targets/ scores/sample_score_e109.json
python xview2_metrics.py scoring/\ 110/predictions/ scoring/\ 110/targets/ scores/sample_score_e110.json
python xview2_metrics.py scoring/\ 111/predictions/ scoring/\ 111/targets/ scores/sample_score_e111.json
python xview2_metrics.py scoring/\ 112/predictions/ scoring/\ 112/targets/ scores/sample_score_e112.json
python xview2_metrics.py scoring/\ 113/predictions/ scoring/\ 113/targets/ scores/sample_score_e113.json
python xview2_metrics.py scoring/\ 114/predictions/ scoring/\ 114/targets/ scores/sample_score_e114.json
python xview2_metrics.py scoring/\ 115/predictions/ scoring/\ 115/targets/ scores/sample_score_e115.json
python xview2_metrics.py scoring/\ 116/predictions/ scoring/\ 116/targets/ scores/sample_score_e116.json
python xview2_metrics.py scoring/\ 117/predictions/ scoring/\ 117/targets/ scores/sample_score_e117.json
python xview2_metrics.py scoring/\ 118/predictions/ scoring/\ 118/targets/ scores/sample_score_e118.json
python xview2_metrics.py scoring/\ 119/predictions/ scoring/\ 119/targets/ scores/sample_score_e119.json
python xview2_metrics.py scoring/\ 120/predictions/ scoring/\ 120/targets/ scores/sample_score_e120.json
python xview2_metrics.py scoring/\ 121/predictions/ scoring/\ 121/targets/ scores/sample_score_e121.json
python xview2_metrics.py scoring/\ 122/predictions/ scoring/\ 122/targets/ scores/sample_score_e122.json
python xview2_metrics.py scoring/\ 123/predictions/ scoring/\ 123/targets/ scores/sample_score_e123.json
python xview2_metrics.py scoring/\ 124/predictions/ scoring/\ 124/targets/ scores/sample_score_e124.json
python xview2_metrics.py scoring/\ 125/predictions/ scoring/\ 125/targets/ scores/sample_score_e125.json
python xview2_metrics.py scoring/\ 126/predictions/ scoring/\ 126/targets/ scores/sample_score_e126.json
python xview2_metrics.py scoring/\ 127/predictions/ scoring/\ 127/targets/ scores/sample_score_e127.json
python xview2_metrics.py scoring/\ 128/predictions/ scoring/\ 128/targets/ scores/sample_score_e128.json
python xview2_metrics.py scoring/\ 129/predictions/ scoring/\ 129/targets/ scores/sample_score_e129.json
python xview2_metrics.py scoring/\ 130/predictions/ scoring/\ 130/targets/ scores/sample_score_e130.json
python xview2_metrics.py scoring/\ 131/predictions/ scoring/\ 131/targets/ scores/sample_score_e131.json
python xview2_metrics.py scoring/\ 132/predictions/ scoring/\ 132/targets/ scores/sample_score_e132.json
python xview2_metrics.py scoring/\ 133/predictions/ scoring/\ 133/targets/ scores/sample_score_e133.json
python xview2_metrics.py scoring/\ 134/predictions/ scoring/\ 134/targets/ scores/sample_score_e134.json
python xview2_metrics.py scoring/\ 135/predictions/ scoring/\ 135/targets/ scores/sample_score_e135.json
python xview2_metrics.py scoring/\ 136/predictions/ scoring/\ 136/targets/ scores/sample_score_e136.json
python xview2_metrics.py scoring/\ 137/predictions/ scoring/\ 137/targets/ scores/sample_score_e137.json
python xview2_metrics.py scoring/\ 138/predictions/ scoring/\ 138/targets/ scores/sample_score_e138.json
python xview2_metrics.py scoring/\ 139/predictions/ scoring/\ 139/targets/ scores/sample_score_e139.json
python xview2_metrics.py scoring/\ 140/predictions/ scoring/\ 140/targets/ scores/sample_score_e140.json
python xview2_metrics.py scoring/\ 141/predictions/ scoring/\ 141/targets/ scores/sample_score_e141.json
python xview2_metrics.py scoring/\ 142/predictions/ scoring/\ 142/targets/ scores/sample_score_e142.json
python xview2_metrics.py scoring/\ 143/predictions/ scoring/\ 143/targets/ scores/sample_score_e143.json
python xview2_metrics.py scoring/\ 144/predictions/ scoring/\ 144/targets/ scores/sample_score_e144.json
python xview2_metrics.py scoring/\ 145/predictions/ scoring/\ 145/targets/ scores/sample_score_e145.json
python xview2_metrics.py scoring/\ 146/predictions/ scoring/\ 146/targets/ scores/sample_score_e146.json
python xview2_metrics.py scoring/\ 147/predictions/ scoring/\ 147/targets/ scores/sample_score_e147.json
python xview2_metrics.py scoring/\ 148/predictions/ scoring/\ 148/targets/ scores/sample_score_e148.json
python xview2_metrics.py scoring/\ 149/predictions/ scoring/\ 149/targets/ scores/sample_score_e149.json
python xview2_metrics.py scoring/\ 150/predictions/ scoring/\ 150/targets/ scores/sample_score_e150.json
python xview2_metrics.py scoring/\ 151/predictions/ scoring/\ 151/targets/ scores/sample_score_e151.json
python xview2_metrics.py scoring/\ 152/predictions/ scoring/\ 152/targets/ scores/sample_score_e152.json
python xview2_metrics.py scoring/\ 153/predictions/ scoring/\ 153/targets/ scores/sample_score_e153.json
python xview2_metrics.py scoring/\ 154/predictions/ scoring/\ 154/targets/ scores/sample_score_e154.json
python xview2_metrics.py scoring/\ 155/predictions/ scoring/\ 155/targets/ scores/sample_score_e155.json
python xview2_metrics.py scoring/\ 156/predictions/ scoring/\ 156/targets/ scores/sample_score_e156.json
python xview2_metrics.py scoring/\ 157/predictions/ scoring/\ 157/targets/ scores/sample_score_e157.json
python xview2_metrics.py scoring/\ 158/predictions/ scoring/\ 158/targets/ scores/sample_score_e158.json
python xview2_metrics.py scoring/\ 159/predictions/ scoring/\ 159/targets/ scores/sample_score_e159.json
python xview2_metrics.py scoring/\ 160/predictions/ scoring/\ 160/targets/ scores/sample_score_e160.json
python xview2_metrics.py scoring/\ 161/predictions/ scoring/\ 161/targets/ scores/sample_score_e161.json
python xview2_metrics.py scoring/\ 162/predictions/ scoring/\ 162/targets/ scores/sample_score_e162.json
python xview2_metrics.py scoring/\ 163/predictions/ scoring/\ 163/targets/ scores/sample_score_e163.json
python xview2_metrics.py scoring/\ 164/predictions/ scoring/\ 164/targets/ scores/sample_score_e164.json
python xview2_metrics.py scoring/\ 165/predictions/ scoring/\ 165/targets/ scores/sample_score_e165.json
python xview2_metrics.py scoring/\ 166/predictions/ scoring/\ 166/targets/ scores/sample_score_e166.json
python xview2_metrics.py scoring/\ 167/predictions/ scoring/\ 167/targets/ scores/sample_score_e167.json
python xview2_metrics.py scoring/\ 168/predictions/ scoring/\ 168/targets/ scores/sample_score_e168.json
python xview2_metrics.py scoring/\ 169/predictions/ scoring/\ 169/targets/ scores/sample_score_e169.json
python xview2_metrics.py scoring/\ 170/predictions/ scoring/\ 170/targets/ scores/sample_score_e170.json
python xview2_metrics.py scoring/\ 171/predictions/ scoring/\ 171/targets/ scores/sample_score_e171.json
python xview2_metrics.py scoring/\ 172/predictions/ scoring/\ 172/targets/ scores/sample_score_e172.json
python xview2_metrics.py scoring/\ 173/predictions/ scoring/\ 173/targets/ scores/sample_score_e173.json
python xview2_metrics.py scoring/\ 174/predictions/ scoring/\ 174/targets/ scores/sample_score_e174.json
python xview2_metrics.py scoring/\ 175/predictions/ scoring/\ 175/targets/ scores/sample_score_e175.json
python xview2_metrics.py scoring/\ 176/predictions/ scoring/\ 176/targets/ scores/sample_score_e176.json
python xview2_metrics.py scoring/\ 177/predictions/ scoring/\ 177/targets/ scores/sample_score_e177.json
python xview2_metrics.py scoring/\ 178/predictions/ scoring/\ 178/targets/ scores/sample_score_e178.json
python xview2_metrics.py scoring/\ 179/predictions/ scoring/\ 179/targets/ scores/sample_score_e179.json
python xview2_metrics.py scoring/\ 180/predictions/ scoring/\ 180/targets/ scores/sample_score_e180.json
python xview2_metrics.py scoring/\ 181/predictions/ scoring/\ 181/targets/ scores/sample_score_e181.json
python xview2_metrics.py scoring/\ 182/predictions/ scoring/\ 182/targets/ scores/sample_score_e182.json
python xview2_metrics.py scoring/\ 183/predictions/ scoring/\ 183/targets/ scores/sample_score_e183.json
python xview2_metrics.py scoring/\ 184/predictions/ scoring/\ 184/targets/ scores/sample_score_e184.json
python xview2_metrics.py scoring/\ 185/predictions/ scoring/\ 185/targets/ scores/sample_score_e185.json
python xview2_metrics.py scoring/\ 186/predictions/ scoring/\ 186/targets/ scores/sample_score_e186.json
python xview2_metrics.py scoring/\ 187/predictions/ scoring/\ 187/targets/ scores/sample_score_e187.json
python xview2_metrics.py scoring/\ 188/predictions/ scoring/\ 188/targets/ scores/sample_score_e188.json
python xview2_metrics.py scoring/\ 189/predictions/ scoring/\ 189/targets/ scores/sample_score_e189.json
python xview2_metrics.py scoring/\ 190/predictions/ scoring/\ 190/targets/ scores/sample_score_e190.json
python xview2_metrics.py scoring/\ 191/predictions/ scoring/\ 191/targets/ scores/sample_score_e191.json
python xview2_metrics.py scoring/\ 192/predictions/ scoring/\ 192/targets/ scores/sample_score_e192.json
python xview2_metrics.py scoring/\ 193/predictions/ scoring/\ 193/targets/ scores/sample_score_e193.json
python xview2_metrics.py scoring/\ 194/predictions/ scoring/\ 194/targets/ scores/sample_score_e194.json
python xview2_metrics.py scoring/\ 195/predictions/ scoring/\ 195/targets/ scores/sample_score_e195.json
python xview2_metrics.py scoring/\ 196/predictions/ scoring/\ 196/targets/ scores/sample_score_e196.json
python xview2_metrics.py scoring/\ 197/predictions/ scoring/\ 197/targets/ scores/sample_score_e197.json
python xview2_metrics.py scoring/\ 198/predictions/ scoring/\ 198/targets/ scores/sample_score_e198.json
python xview2_metrics.py scoring/\ 199/predictions/ scoring/\ 199/targets/ scores/sample_score_e199.json
